# Generated by Django 5.2.11 on 2026-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmersmarket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UGX", "UGX - Ugandan Shilling"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("TZS", "TZS - Tanzanian Shilling"),
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                ],
                default="UGX",
                max_length=3,
            ),
        ),
    ]
