# Generated by Django 5.2.11 on 2026-05-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmersmarket", "0002_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vegetables", "🥬 Vegetables"),
                    ("fruits", "🍎 Fruits"),
                    ("grains", "🌾 Grains & Cereals"),
                    ("dairy", "🥛 Dairy & Eggs"),
                    ("herbs", "🌿 Herbs & Spices"),
                    ("legumes", "🫘 Legumes & Pulses"),
                    ("roots", "🥕 Roots & Tubers"),
                    ("other", "📦 Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(
                blank=True, help_text="When was this harvested?", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("g", "g (grams)"),
                    ("bunch", "Bunch"),
                    ("piece", "Piece"),
                    ("litre", "Litre"),
                    ("crate", "Crate"),
                    ("bag", "Bag"),
                    ("dozen", "Dozen"),
                ],
                default="kg",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Preparing", "Preparing"),
                    ("Ready", "Ready for Pickup/Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp",
                        to="farmersmarket.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField()),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="farmersmarket.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="farmersmarket.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "client")},
            },
        ),
    ]
