# Generated by Django 5.2.11 on 2026-05-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmersmarket",
            "0003_product_category_product_harvest_date_product_unit_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryOTP",
        ),
    ]
