# Generated by Django 5.2.15 on 2026-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmersmarket",
            "0005_order_delivered_at_alter_order_status_courier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
