# Generated by Django 5.2.6 on 2026-06-21 18:39

import django.core.validators
import django.db.models.deletion
import farmersmarket.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0006_notification_email_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Order', 'New Order'), ('Payment', 'Payment'), ('Status', 'Order Status Update'), ('Product', 'Product Availability'), ('Delivery', 'Delivery Confirmation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='crop_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Crop name can only contain letters, spaces, hyphens, and apostrophes.', regex="^[A-Za-z\\s'-]+$")]),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_code', models.CharField(default=farmersmarket.models.generate_payment_code, max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='farmersmarket.order')),
            ],
        ),
    ]
