# Generated by Django 5.2.6 on 2026-06-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0007_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
