# Generated by Django 5.2.6 on 2026-06-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0007_order_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
    ]
