# Generated by Django 5.2.6 on 2026-06-21 20:41

from django.db import migrations, models
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0007_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
