# Generated by Django 5.2.6 on 2026-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0008_auto_20260621_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_confirmed_by_client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Order', 'New Order'), ('Payment', 'Payment'), ('Status', 'Order Status Update'), ('Product', 'Product Availability')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='crop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
