# Generated by Django 5.2.6 on 2026-06-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0008_payment_payment_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_confirmed',
        ),
    ]
