# Generated by Django 5.2.6 on 2026-06-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0009_remove_payment_payment_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
    ]
