# Generated by Django 6.0.6 on 2026-06-22 10:01

import django.utils.timezone
import farmersmarket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0010_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),
        migrations.AddField(
            model_name='payment',
            name='client_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(default=farmersmarket.models.generate_payment_code, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Card', 'Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
