# Generated by Django 6.0.6 on 2026-06-22

from django.db import migrations, models
import random
import string


def generate_unique_codes(apps, schema_editor):
    Payment = apps.get_model("farmersmarket", "Payment")

    used_codes = set()

    for payment in Payment.objects.all():
        code = ''.join(
            random.choices(
                string.ascii_uppercase + string.digits,
                k=8
            )
        )

        while code in used_codes:
            code = ''.join(
                random.choices(
                    string.ascii_uppercase + string.digits,
                    k=8
                )
            )

        payment.payment_code = code
        payment.save(update_fields=["payment_code"])

        used_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0010_receipt'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),

        migrations.AddField(
            model_name='payment',
            name='client_message',
            field=models.TextField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='payment',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='payment',
            name='confirmed_by_client',
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(
                max_length=8,
                null=True,
                blank=True
            ),
        ),

        migrations.RunPython(generate_unique_codes),

        migrations.AlterField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(
                max_length=8,
                unique=True
            ),
        ),

        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Confirmed', 'Confirmed'),
                    ('Failed', 'Failed')
                ],
                default='Pending',
                max_length=20
            ),
        ),

        migrations.AddField(
            model_name='payment',
            name='time_created',
            field=models.DateTimeField(
                auto_now_add=True
            ),
        ),

        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Cash', 'Cash'),
                    ('Mobile Money', 'Mobile Money'),
                    ('Card', 'Card')
                ],
                max_length=20,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='payment',
            name='time_paid',
            field=models.DateTimeField(
                blank=True,
                null=True
            ),
        ),
    ]