# Generated by Django 6.0.6 on 2026-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0011_remove_payment_is_successful_payment_client_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
