# Generated by Django 6.0.6 on 2026-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0012_alter_payment_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
