# Generated by Django 6.0.6 on 2026-06-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0013_orderitem_customer_confirmed_orderitem_delivery_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_confirmed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_code',
        ),
    ]
