# Generated by Django 6.0.6 on 2026-06-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0014_remove_orderitem_customer_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
