# Generated by Django 6.0.6 on 2026-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0015_order_customer_received_order_payment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_received_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_code_sent',
            field=models.BooleanField(default=False),
        ),
    ]
