# Generated by Django 6.0.6 on 2026-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0016_order_client_received_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_code_sent',
            new_name='payment_details_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
