# Generated by Django 6.0.6 on 2026-06-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0017_rename_payment_code_sent_order_payment_details_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_received_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_details_sent',
        ),
    ]
