# Generated by Django 6.0.6 on 2026-06-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersmarket', '0020_order_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation_code',
        ),
    ]
